### ISSUE TITLE
Problem m. parsing af dato

### ISSUE THREAD

**Issue by styrke10** [mapcentia/AtomMatrikel#1]
Hej Martin,
Jeg har eksperimenteret lidt med din replikator. Hos mig går den ned med følgende fejl:
------------------------
Connecting to database: jdbc:postgresql://localhost:5432/Matrikel

Henter Atom feed....

Feed Titel: Det digitale matrikelkort

Sidste entry: 1970-01-01 00:00:00

Forbindelse etableret...

--------------

Published Date: Tue Aug 22 02:31:21 CEST 2017

Link: ftp://ftp.kortforsyningen.dk/atomfeeds/MATRIKELKORT/ATOM/GML/2008251_GML_UTM32-EUREF89.zip
Exception in thread "main" java.text.ParseException: Unparseable date: "Tue Aug 22 02:31:21 CEST 2017"
        at java.text.DateFormat.parse(Unknown Source)
        at com.mapcentia.matrikel.Track.storeInDb(Track.java:38)
        at com.mapcentia.matrikel.Downloader.read(Downloader.java:84)
        at com.mapcentia.matrikel.Main.main(Main.java:28)
------------------------

Kan det tænkes, at der er noget server-specifik dato-format-opsætning, som jeg misser??

mvh,
Morten

**Comment by mapcentia** [comment]
Hej Morten og tak fordi du tester!
Det er sikkert fordi dit OS har dansk local. Nu har jeg sat English explicit i SimpleDateFormat. Der er pushed en ny jar-fil.

**Comment by styrke10** [comment]
Hej Martin,
Det hjalp på problemet med datoen - nu kører rutinen lystigt og har gjort det siden engang i formiddags - den downloader ejerlav og skriver at de indsættes i tabellerne - men der kommer intet ind i PostGIS!
Jeg formoder, at de burde loades ind løbende? Der bliver ikke oprettet tabeller overhovedet!
Er der monstro en forklaring herpå?

**Comment by mapcentia** [comment]
Det kører i en BEGIN/COMMIT block (herunder også CREATE TABLE), så det er først når alt er hentet der laves en commit. Det forhindrer en partial opdatering.

**Comment by styrke10** [comment]
Glimrende! Jeg lader det hele køre - og giver en melding, når den er igennem! :-)

**Comment by styrke10** [comment]
Thumbs up! Det er kørt igennem uden problemer! Jeg har nu et landsdækkende matrikelkort! :-)
Et ønske til næste version kunne være muligheden for at konfigurere et subset af ejerlav, som man var interesseret i - og kun downloade og vedligeholde dette subset! ;-)

**Comment by mapcentia** [comment]
Det er godt at høre! Nu burde du kunne køre kommandoen dagligt og have et opdateret matrikelkort. Det med subset af ejerlav lægger jeg en som en Request.
